AWSTemplateFormatVersion: 2010-09-09
Description: Mitjan CloudFormation -testitemplate

Resources:
  mitjabucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mitja-cf-bucket

  munjono:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: mitjan-jono

  ec2eka:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06ad9296e6cf1e3cf
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: mitja-cf-ec2
      SecurityGroupIds:
        - !Ref ec2sg

  ec2sg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ec2 security group
      GroupName: mitja-cf-ec2-sg
      SecurityGroupIngress:
        - FromPort: 80
          IpProtocol: -1
          SourceSecurityGroupId: !Ref lbsg
      Tags:
        - Key: Name
          Value: mitja-cf-ec2-sg
      VpcId: vpc-16908771

  lbsg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: lb security group
      GroupName: mitja-cf-lb-sg
      Tags:
        - Key: Name
          Value: mitja-cf-lb-sg
      VpcId: vpc-16908771

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: mitja-cf-lb
      Scheme: internet-facing
      SecurityGroups:
        - !Ref lbsg
      SubnetMappings:
        - SubnetId: subnet-05fa212e
        - SubnetId: subnet-bac919f2
        - SubnetId: subnet-b10a08ea


Outputs:
  LoadBalancerDNS:
    Value: !GetAtt LoadBalancer.DNSName

